prs/test
iasemenov/testing pull request #27
Opened 2019-03-26 16:17 UTC by iasemenov

2019-03-26 16:18 UTC, iasemenov commented on pushtest
> +abrivalg
added

2019-03-26 16:47 UTC, iasemenov commented on pushtest
>  12345
delete_

2019-03-26 17:01 UTC, iasemenov commented on pushtest
> -forth
removed forth line

2019-03-26 17:14 UTC, iasemenov commented on pushtest
> +4
первая строка последнего коммита

2019-03-26 17:15 UTC, iasemenov commented on pushtest
> +4
первая строка последнего коммита 2

2019-03-26 17:25 UTC, iasemenov commented on pushtest
> -34
remove end 3

2020-04-26 14:32 UTC, iasemenov commented
testcomment

2020-04-26 14:54 UTC, iasemenov reviewed
123

2020-05-07 17:20 UTC, iasemenov commented on pushtest
>  test
test

2020-05-07 17:20 UTC, iasemenov commented on pushtest
>  testtesttest
test

2020-05-14 13:08 UTC, iasemenov commented on pushtest
>  test
review

2020-05-14 13:08 UTC, iasemenov commented on pushtest
>  prtestsdf
testcomment

2020-05-14 14:26 UTC, iasemenov commented on pushtest
> -abrivalg
reply no pending

2020-05-14 14:30 UTC, iasemenov commented on pushtest
> -abrivalg
reply no pending 2

2020-05-14 14:33 UTC, iasemenov commented on pushtest
> -abrivalg
reply no pending 3

2020-05-28 17:41 UTC, iasemenov reviewed
113

2020-05-28 17:44 UTC, iasemenov reviewed
test2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1233

2020-06-11 14:35 UTC, iasemenov commented
test

2020-06-11 14:35 UTC, iasemenov commented
test2

2020-06-16 10:01 UTC, iasemenov commented
test delete

2020-06-16 10:16 UTC, iasemenov commented
cmnt

2020-06-16 10:45 UTC, iasemenov commented
testcmnt

2020-06-16 10:46 UTC, iasemenov commented
delete

2020-06-16 10:48 UTC, iasemenov commented
dlt

2020-06-16 12:13 UTC, iasemenov commented
cmnt

2020-06-17 11:14 UTC, iasemenov commented
comment

2020-06-17 15:03 UTC, iasemenov commented on pushtest
> +abrivalg
```suggestion
abri
```

2020-06-17 15:05 UTC, iasemenov commented on pushtest
> +abrivalg
```
somecode
```

2020-06-17 15:21 UTC, iasemenov commented on pushtest
> +test
```somecode```

2020-06-17 15:53 UTC, iasemenov commented on pushtest
> +test
>somecode
incorrect

2020-06-22 16:07 UTC, iasemenov reviewed
123

2020-07-23 10:22 UTC, iasemenov commented
comment

2020-07-23 10:24 UTC, iasemenov reviewed
another review 1231234

2020-07-23 10:24 UTC, iasemenov commented on pushtest
>  testtesttest
file comment

2020-07-23 10:28 UTC, iasemenov commented on pushtest
> +abrivalg
comment review

2020-07-23 10:30 UTC, iasemenov commented on pushtest
> +asdf
fiel comment from browser

2023-01-18 14:08 UTC, iasemenov commented on pushtest
> +asdf
test

2023-01-18 14:11 UTC, iasemenov commented on pushtest
>  prtestsdf
test

2023-01-18 14:11 UTC, iasemenov commented on pushtest
>  prtestsdf
asdfasdf

2023-01-27 14:50 UTC, iasemenov commented on pushtest
> +21
tst

2023-01-27 14:50 UTC, iasemenov commented on pushtest
> +21
tst

2023-01-27 15:10 UTC, iasemenov commented on pushtest
> +раз
tst

2023-02-10 14:53 UTC, iasemenov commented on pushtest
> -test
on removed lines 2

2023-03-27 17:22 UTC, iasemenov commented on pushtest
> +три
123

2023-03-27 17:22 UTC, iasemenov commented on pushtest
> +16
123

2023-03-27 17:23 UTC, iasemenov commented on pushtest
> +22
123

2023-03-27 17:23 UTC, iasemenov commented on pushtest
> +10
123

2023-03-27 17:23 UTC, iasemenov commented on pushtest
> +6
123

2023-08-24 15:18 UTC, Naid405 commented on pushtest
> +6
```java
@NotNull
  public static IntPair getGutterArea(@NotNull Editor editor, int xOffset) {
    EditorGutterComponentEx gutter = ((EditorEx)editor).getGutterComponentEx();
    int x = xOffset + 1; // leave 1px for brace highlighters
    if (ExperimentalUI.isNewUI()) {
      x += gutter.getExtraLineMarkerFreePaintersAreaOffset();
      x += 2; //IDEA-286352
      return new IntPair(x, x + (int)(JBUIScale.scale(JBUI.getInt("Gutter.VcsChanges.width", 4) * getEditorScale(editor))));
    }
    else {
      x += gutter.getLineMarkerFreePaintersAreaOffset();
    }
    int endX = gutter.getWhitespaceSeparatorOffset();
    return new IntPair(x, endX);
  }

  public static boolean isInsideMarkerArea(@NotNull MouseEvent e) {
    final EditorGutterComponentEx gutter = (EditorGutterComponentEx)e.getComponent();
    return gutter.isInsideMarkerArea(e);
  }
```

2023-10-09 15:27 UTC, Naid405 commented on pushtest
> +11
123

2023-11-05 11:35 UTC, Naid405 reviewed
???1

2023-11-05 11:35 UTC, Naid405 approved these changes
123

2023-11-05 11:36 UTC, Naid405 requested changes
123

2023-11-27 16:56 UTC, iasemenov commented
123

2023-11-28 16:06 UTC, iasemenov commented
123124

2023-12-09 12:24 UTC, iasemenov commented
123

2023-12-11 17:39 UTC, iasemenov commented on pushtest
>  testtesttest
123

2023-12-11 17:39 UTC, iasemenov commented on pushtest
>  testtesttest
123123

2023-12-11 17:45 UTC, iasemenov commented on pushtest
> +16
123

2023-12-11 17:45 UTC, iasemenov commented on pushtest
> +16
12345

2023-12-20 16:52 UTC, Naid405 commented on pushtest
>  testtesttest
123

2023-12-20 16:52 UTC, Naid405 commented on pushtest
>  testtesttest
123

2023-12-20 16:53 UTC, Naid405 commented on pushtest
>  testtesttest
123

2023-12-20 16:55 UTC, iasemenov commented on pushtest
>  test
123

2023-12-21 15:18 UTC, iasemenov commented on pushtest
> +раз
123

2023-12-21 15:27 UTC, iasemenov commented on pushtest
> +second
123

2024-01-15 14:05 UTC, iasemenov commented on pushtest
>  testtesttest
123

2024-01-15 16:38 UTC, iasemenov commented on pushtest
> +test
123

2024-01-15 18:14 UTC, iasemenov commented on pushtest
> +12345
123

2024-01-16 11:30 UTC, iasemenov commented on pushtest
>  test
123

2024-01-16 11:40 UTC, iasemenov commented on pushtest
> +test
123

2024-01-16 11:40 UTC, iasemenov commented on pushtest
>  prtestsdf
123

2024-01-19 17:21 UTC, closed without merging